import { Calendar, Search, Shield } from "lucide-react"
import { mockAuditLogs } from "@/lib/mock-data"
import { Badge } from "@/components/ui/badge"
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"
import { Input } from "@/components/ui/input"
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select"
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table"
import { StatCard } from "@/components/dashboard/stat-card"

function formatDate(dateString: string) { return new Date(dateString).toLocaleString("en-IN", { day: "numeric", month: "short", hour: "2-digit", minute: "2-digit" }) }

export default function AdminAuditLogsPage() {
  return <div className="space-y-6"><div><h2 className="text-2xl font-bold tracking-tight text-foreground">Audit Logs</h2><p className="text-muted-foreground">Track important admin actions for accountability and transparency.</p></div><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><StatCard title="Total Actions" value={mockAuditLogs.length} description="Logged events" icon={Shield} variant="default" /><StatCard title="Today’s Actions" value="5" description="Recent changes" icon={Calendar} variant="accent" /><StatCard title="Admin Actions" value="4" description="Manual updates" icon={Shield} variant="warning" /><StatCard title="System Alerts" value="1" description="SLA warnings" icon={Shield} variant="destructive" /></div><Card><CardHeader><CardTitle>Filters</CardTitle><CardDescription>Search audit events by actor, action type, or entity.</CardDescription></CardHeader><CardContent><div className="grid gap-3 md:grid-cols-4"><div className="relative md:col-span-2"><Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-muted-foreground" /><Input placeholder="Search logs..." className="pl-9" /></div><Select><SelectTrigger><SelectValue placeholder="Action Type" /></SelectTrigger><SelectContent><SelectItem value="status">Status Updated</SelectItem><SelectItem value="priority">Priority Changed</SelectItem><SelectItem value="resolved">Report Resolved</SelectItem></SelectContent></Select><Select><SelectTrigger><SelectValue placeholder="Actor Role" /></SelectTrigger><SelectContent><SelectItem value="admin">Admin</SelectItem><SelectItem value="officer">Officer</SelectItem><SelectItem value="system">System</SelectItem></SelectContent></Select></div></CardContent></Card><Card><CardHeader><CardTitle>Audit Trail</CardTitle><CardDescription>Read-only action history.</CardDescription></CardHeader><CardContent className="overflow-x-auto"><Table><TableHeader><TableRow><TableHead>Actor</TableHead><TableHead>Action</TableHead><TableHead>Entity</TableHead><TableHead>Time</TableHead><TableHead>Description</TableHead></TableRow></TableHeader><TableBody>{mockAuditLogs.map((log) => <TableRow key={log.id}><TableCell className="font-medium">{log.performedBy}</TableCell><TableCell><Badge variant="outline">{log.action}</Badge></TableCell><TableCell>{log.targetType} • {log.targetId}</TableCell><TableCell>{formatDate(log.performedAt)}</TableCell><TableCell className="max-w-xl">{log.description}</TableCell></TableRow>)}</TableBody></Table></CardContent></Card></div>
}
